version: '3.8'

services:
  postgres:
    container_name: postgres-rest
    image: postgres:15.1-alpine
    restart: on-failure
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5435:5432
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "${POSTGRES_USER}", "-d","postgres-rest" ]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 80s

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    volumes:
      - redis_data:/data
    expose:
      - "6379"
    ports:
      - "6379:6379"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5

  ray_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ray_api
    depends_on:
       postgres:
         condition: service_healthy
       redis:
         condition: service_healthy
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always
    tty: true
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  celery:
    build: .
    command: celery -A ray_api worker -l info -P solo
    depends_on:
      - ray_api
      - redis
  celery_beat:
    build: .
    volumes:
      - celery_beat:/data
    command: celery -A ray_api beat
    depends_on:
      - ray_api
      - redis
volumes:
  postgres_data:
  redis_data:
  celery_beat:
  static_value:
